version: "3.9"

services:
  backend:
    build:
      context: ./backend/docker
    container_name: lion-backend

    command: >
      sh -c "
      cd /var/www/html &&
      if [ ! -f .env ]; then
        cp .env.example .env;
      fi &&
      if [ ! -f database/database.sqlite ]; then
        touch database/database.sqlite;
      fi &&
      composer install --no-interaction &&
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php-fpm -F
      "

    volumes:
      # Código (bind mount)
      - ./backend/src:/var/www/html

      # Volúmenes Docker reales (NO NTFS)
      - backend_storage:/var/www/html/storage
      - backend_bootstrap_cache:/var/www/html/bootstrap/cache

    networks:
      - lion_net

  web:
    image: nginx:alpine
    container_name: lion-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - lion_net

  frontend:
    image: node:20-alpine
    container_name: lion-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173 --force"
    networks:
      - lion_net

networks:
  lion_net:
    driver: bridge

volumes:
  backend_storage:
  backend_bootstrap_cache:
