services:
  backend:
    build:
      context: ./backend/docker
    container_name: lion-backend
    volumes:
      - ./backend/src:/var/www/html
    networks:
      - lion_net

  web:
    image: nginx:alpine
    container_name: lion-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - lion_net

  frontend:
    build:
      context: ./frontend
    container_name: lion-frontend
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - lion_net

networks:
  lion_net:
    driver: bridge
