services:
  backend:
    build:
      context: ./backend/docker
    container_name: lion-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - lion_net

  web:
    image: nginx:alpine
    container_name: lion-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - lion_net

  frontend:
    build:
      context: ./frontend
    container_name: lion-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - lion_net

networks:
  lion_net:
    driver: bridge
